services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin                      # Admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin                  # Admin password
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana                     # Persistent data storage
      - ./dashboards:/etc/grafana/provisioning/dashboards # Provision dashboards
      - ./datasources:/etc/grafana/provisioning/datasources # Provision data sources
    ports:
      - "3100:3000"  # Grafana UI
    restart: unless-stopped
    networks:
      - monitoring  # Attach to the shared network

networks:
  monitoring:
    external: true  # Use the existing shared network
    
volumes:
  grafana_data:
