services:
  wunderground_exporter:
    build:
      context: .
      dockerfile: wunderground.dockerfile
    container_name: wunderground_exporter
    ports:
      - "9123:9123"  # Map container port 9123
    restart: unless-stopped
    networks:
      - monitoring  # Connect to the shared network
  
  prometheus:
    build:
      context: .
      dockerfile: prometheus.dockerfile  # Use the custom Dockerfile
    container_name: prometheus
    volumes:
      - prometheus_data:/etc/prometheus  # Volume for runtime data
    ports:
      - "9090:9090"  # Prometheus UI
    depends_on:
      - wunderground_exporter
    restart: unless-stopped
    networks:
      - monitoring  # Connect to the shared network

volumes:
  prometheus_data:

networks:
  monitoring:
    name: monitoring  # Ensure this name is consistent across files
    driver: bridge
