
services:
  wunderground_exporter:
    build:
      context: .
      dockerfile: wunderground.dockerfile
    container_name: wunderground_exporter
    ports:
      - "9123:9123"  # Map container port 9123
    restart: unless-stopped
  
  prometheus:
    build:
      context: .
      dockerfile: prometheus.dockerfile  # Use the custom Dockerfile
    container_name: prometheus
    volumes:
      - prometheus_data:/etc/prometheus  # Volume for runtime data
    ports:
      - "9090:9090"  # Prometheus UI
    depends_on:
      - wunderground_exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin                      # Admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin                  # Admin password
      - GF_SERVER_HTTP_PORT=3010  # Explicitly set Grafana HTTP port
    volumes:
      - grafana_data:/var/lib/grafana                     # Persistent data storage
    ports:
      - "3010:3010"  # Grafana UI
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana_data:
  prometheus_data:
