
services:
  wunderground_exporter:
    build:
      context: .
      dockerfile: wunderground.dockerfile
    container_name: wunderground_exporter
    ports:
      - "9123:9123"  # Map container port 9123
    restart: unless-stopped
    volumes:
      - ./config:/app/config  # Mount the configuration directory for Wunderground Exporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro  # Main Prometheus configuration
      - ./rules:/etc/prometheus/rules:ro                   # Directory for alerting rules
    ports:
      - "9090:9090"  # Prometheus UI
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin                      # Admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin                  # Admin password
    volumes:
      - ./provisioning:/etc/grafana/provisioning          # Grafana provisioning configuration
      - ./dashboards:/etc/grafana/dashboards              # Grafana dashboards directory
      - grafana_data:/var/lib/grafana                     # Persistent data storage
    ports:
      - "3000:3000"  # Grafana UI
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana_data:
